title: Department of Special Affairs
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs
color_scheme: dsa

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
